name: Quality

on:
  push:
    branches: [trunk]
  pull_request:

permissions:
  contents: read

jobs:
  lint-php:
    name: PHP Lint
    uses: ahegyes/wordpress-configs/.github/workflows/reusable-php-lint.yml@714fc2a66d6ae5011999beb18a4b01fb1992f4bd
    with:
      php-version: '8.5'
      scripts: '["lint:php:phpcs", "lint:php:phpstan"]'

  changelog:
    name: Changelog fragments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.5'
          coverage: none
          tools: composer:v2
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
      - run: composer changelog:validate

  readme-lint:
    name: readme.txt lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: thetwopct/wporg-plugin-readme-linter@1f869aba959265ecc90935b2380c6569d56646ac # v1.0.2
        with:
          path: readme.txt
          fail-on: error
